// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtNJ-_r9y05p0gkPQtB5b-Rd2f0Rbo7YI',
    appId: '1:977290258719:web:4ec177e1a7f373e4e6282a',
    messagingSenderId: '977290258719',
    projectId: 'ledgerapp-de304',
    authDomain: 'ledgerapp-de304.firebaseapp.com',
    storageBucket: 'ledgerapp-de304.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4hrgtdh02HfzuNGyReJQIXHExdDanlY',
    appId: '1:977290258719:android:75f2a2b14dd7ef1ae6282a',
    messagingSenderId: '977290258719',
    projectId: 'ledgerapp-de304',
    storageBucket: 'ledgerapp-de304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiiCraZiTnSXi2-ptA6-h3DNDLNvv94_I',
    appId: '1:977290258719:ios:c9fd3171fc8ae2dde6282a',
    messagingSenderId: '977290258719',
    projectId: 'ledgerapp-de304',
    storageBucket: 'ledgerapp-de304.appspot.com',
    iosClientId: '977290258719-m9p6jpj3acrhkf37h12ei1m47939q26q.apps.googleusercontent.com',
    iosBundleId: 'com.pramod.ledger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiiCraZiTnSXi2-ptA6-h3DNDLNvv94_I',
    appId: '1:977290258719:ios:c9fd3171fc8ae2dde6282a',
    messagingSenderId: '977290258719',
    projectId: 'ledgerapp-de304',
    storageBucket: 'ledgerapp-de304.appspot.com',
    iosClientId: '977290258719-m9p6jpj3acrhkf37h12ei1m47939q26q.apps.googleusercontent.com',
    iosBundleId: 'com.pramod.ledger',
  );
}
